### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuario (3)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#10]
Al hacer click en el botón "Volver".
![volver](https://cloud.githubusercontent.com/assets/27014552/24867649/3d77d238-1de4-11e7-9927-8668a602ff2c.jpg)

Devuelve msj de error. 

![altausuariobotvolver](https://cloud.githubusercontent.com/assets/27014552/24867667/4b9c31ce-1de4-11e7-9a33-98d0c6566230.jpg)

**Comment by leoimoli** [comment]
Se subió a testing el 18/04.
