### ISSUE TITLE
Siniestros/ Versión 1.0/ Informacion del Usuario(1)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#11]
Al querer cambiar la contraseña del usuario, al darle guardar devuelve msj de error. 

![btndesahbilitarconsultaperfiles](https://cloud.githubusercontent.com/assets/27014552/24868051/4e9608d6-1de5-11e7-99e1-bdb888352b8f.jpg)

**Comment by leoimoli** [comment]
Se subió a testing el 18/04.
