### ISSUE TITLE
Legales/ Versión 1.0/ Normativa ANSV (1)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#12]
Cuando se quiere realizar una búsqueda
![nor1](https://cloud.githubusercontent.com/assets/27014552/24960304/c1631e9e-1f6b-11e7-918a-f7c891a3fdc9.jpg)

Y le damos click al botón cancelar o vamos a otra pantalla
![nor2](https://cloud.githubusercontent.com/assets/27014552/24960364/f7c547dc-1f6b-11e7-8c8d-905984488600.jpg)

Y volvemos a la pantalla de búsqueda no refresca los campos (este error se replica en todas las pantallas de búsquedas).

* Agregar tilde a Búsqueda en todas las pantallas.

**Comment by leodimonio** [comment]
Para el lunes va a estar en testing al mediodia

**Comment by leodimonio** [comment]
http://ansvqa09:8080/legales.testing/ ya se encuentra en testing

**Comment by LeandroImoli** [comment]
* Si bien los campos se vacían bien, ahora lo que se muestra mal es en la grilla:
Si se realiza una consulta en primera instancia muestra bien el resultado

![norbus2](https://cloud.githubusercontent.com/assets/27014552/25132786/0c1f4caa-2421-11e7-936f-037efb70d6c0.jpg)

pero cuando vamos a otra pantalla ej: "Convenios Suscriptos" y consultamos por el área "CNRT" 
![conv1](https://cloud.githubusercontent.com/assets/27014552/25132975/b12aaa78-2421-11e7-9775-8a7a40842f48.jpg)

Cuando volvemos a la pantalla "NORMATIVA ANSV" la grilla está mostrando los datos del área  "CNRT" con el nombre de "Banco Mundial"
![nor3](https://cloud.githubusercontent.com/assets/27014552/25133161/3d0815b2-2422-11e7-9a69-954b769b588d.jpg)

Si se realiza una búsqueda en una pantalla no debería modificar la de otra pantalla....

**Comment by leodimonio** [comment]
Se genero búsquedas de dirección o Área independientes para Normativa ANSV y Convenios Suscriptos.
