### ISSUE TITLE
Legales/ Versión 1.0/ Adhesiones (1)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#14]
En esta pantalla si se modifica una Provincia/Municipio a las leyes... 
![adhe1](https://cloud.githubusercontent.com/assets/27014552/24971934/02d8e6f0-1f90-11e7-9168-ff8e3c408743.jpg)

Volvemos a la pestaña adhesiones y luego a la de modificar, encontramos cargados los campos con la última modificación que se realizó.

![adh21](https://cloud.githubusercontent.com/assets/27014552/24972012/468ccf06-1f90-11e7-90cc-6edd8cad6b39.jpg)

* En esta pantalla también sucede el error de la búsqueda que no refresca los campos luego de realizar una consulta.

**Comment by leodimonio** [comment]
se estima para el lunes a la tarde conjunto a los ticket #13 #12

**Comment by leodimonio** [comment]
http://ansvqa09:8080/legales.testing/ ya se encuentra en testing
