### ISSUE TITLE
Legales/ Versión 1.0 / Normativa ANSV (2)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#15]
Al querer intentar agregar una normativa nueva que ya existe, si bien devuelve msj de error pero se debería quitar del msj "Tema Disposición" ya que no se encuentra mas en el sistema ese campo.
![tema](https://cloud.githubusercontent.com/assets/27014552/25133640/a1d5de1a-2423-11e7-9e17-355051cce8a2.jpg)

**Comment by leodimonio** [comment]
Se cambio el texto por Objeto de la Disposición ya que existe el campo.
