### ISSUE TITLE
Legales/ Versión 1.0/ Adhesión (2)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#16]
Cuando se selecciona una provincia que no tenga cargadas municipios, el campo "municipio" deberá estar deshabilitado.
* Este mismo punto replicarlo en la pantalla "CONVENIOS SUSCRIPTOS" en búsqueda y alta.

![adhe2](https://cloud.githubusercontent.com/assets/27014552/25136810/5efd97d2-242c-11e7-984c-fa50d307bc10.jpg)

**Comment by leodimonio** [comment]
Si la provincia no posee municipios el campo se muestra des-habilitado al momento de seleccionar la provincia. Esto se corrigio en ADHESIONES (Adhesiones y Modificar) y en CONVENIOS SUSCRIPTOS(Busqueda y Agregar).
