### ISSUE TITLE
Legales/ Versión 1.0

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#17]
Ej: 
* en caso de estar en una pantalla de alta (o cualquier otra) con algún campo cargado y le damos a la tecla F5 la pantalla se deberá volver a cargar y dejar los campos vacíos, hoy te desloguea del sistema y debes volver a loguearte.

**Comment by leodimonio** [comment]
Al apretar la tecla F5 refresca la pantalla en la cual se encuentra el sistema, en cada panel y en cada solapa.

**Comment by LeandroImoli** [comment]
* Replicar en la pantalla en la pantalla "Normativa Nacional". Al darle F5 solo borra "Tema Normativa" y "Tipo Normativa".
