### ISSUE TITLE
Legales/ Versión 1.0/ Tipo de Fuente

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#18]
* Cambiar EL TIPO de la fuente de los títulos para que esté todo de la misma manera.

![fuente](https://cloud.githubusercontent.com/assets/27014552/25143782/17bad9e6-2442-11e7-9ba8-69fc47ca5c10.jpg)

![fuente2](https://cloud.githubusercontent.com/assets/27014552/25143804/28a4af16-2442-11e7-8444-684e0a00cb96.jpg)

**Comment by leodimonio** [comment]
se hicieron pruebas con la fuente solicitada y no se ve tan nitida como la que se encuentra en este momento, dejo adjuntas las pruebas.

![](https://cloud.githubusercontent.com/assets/17170028/25189330/3d0e19e8-24ff-11e7-95f8-af235c0dd285.jpg)

![](https://cloud.githubusercontent.com/assets/17170028/25189331/3d185f3e-24ff-11e7-98b5-5836d57c4f68.jpg)
