### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuarios (4)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#19]
* Deja crear usuarios ya existentes, debería validar si el "Nombre de Usuario" ya existe.
* Permite crear un usuario que ya existe pero con distinto perfil. Ej: el usuario "36273257" tiene perfil Administrador y de Consulta.

![usuarioperfil](https://cloud.githubusercontent.com/assets/27014552/25182186/331c82e0-24ea-11e7-963f-72aa5a46be1f.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
