### ISSUE TITLE
Siniestros/ Versión 1.0/ Consultar Usuarios (1)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#20]
* Si se desactiva un usuario.
![desactivar](https://cloud.githubusercontent.com/assets/27014552/25183382/cbe1c942-24ed-11e7-8612-de426208433b.jpg)
Permite seguir logueandote con el usuario que se encuentra "desactivado".

* Si me encuentro en la Pág. 2 de la grilla y quiero desactivar un usuario al hacer click en el botón "Desactivar" me lleva a la Pág. 1, me tendría que mantener en la Página que me encuentro.

**Comment by LeandroImoli** [comment]
* No debe mostrar la descripción "No ha sido dado de baja" cuando un usuario NO está dado de baja.
![dadobaja](https://cloud.githubusercontent.com/assets/27014552/25278313/d476a3b6-2678-11e7-96da-6679eb1ba1a2.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.

**Comment by LeandroImoli** [comment]
* Cuando se quiere Activar o Desactivar un usuario, cuando hacemos click sobre el botón refresca la 
pantalla, debería seguir mostrando la grilla.
![re1](https://cloud.githubusercontent.com/assets/27014552/25748077/38a4e23c-3180-11e7-8eea-74cf6c76d2b0.jpg)
![re2](https://cloud.githubusercontent.com/assets/27014552/25748122/6f270fa6-3180-11e7-987a-918617f95081.jpg)

* Cuando se quiera editar un usuario los campos "Contraseña" deberán aparecer deshabilitados, se deberá agregar un botón "Resetear Contraseña" que mostrará los tres campos "Contraseña" (TODOS DEBEN SER OBLIGATORIOS).
- Contraseña Actual.
- Nueva Contraseña.
- Repetir Contraseña.
Cambiar el botón "Volver" por "Cancelar".

* Alinear botón "Consultar"
![alinearr](https://cloud.githubusercontent.com/assets/27014552/25749257/430aa474-3184-11e7-953f-9a4b31924df3.jpg)

**Comment by LeandroImoli** [comment]
* Cuando se quiera editar un usuario los campos "Contraseña" deberán aparecer deshabilitados, se deberá agregar un botón "Resetear Contraseña" que mostrará los tres campos "Contraseña" (TODOS DEBEN SER OBLIGATORIOS).
* Contraseña Actual.
* Nueva Contraseña.
* Repetir Contraseña. (No Funciona). * Al darle guardar sin completar los campos contraseña rompe 
![404](https://cloud.githubusercontent.com/assets/27014552/26118610/eea5dc08-3a40-11e7-88ae-210e8fdd6ac3.jpg)
