### ISSUE TITLE
Siniestros/ Versión 1.0/ Registro Siniestro, Datos Denunciante(1)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#21]
* Fecha de Carga no podrá ser mayor a la fecha actual, si se carga a mano la fecha permite cargar mayor a la del día de hoy

* El control “Mail” es el único que permitirá caracteres especiales (Ej: “@”, “.”), permite cargar caracteres especiales en cualquier campo.

![denunciante](https://cloud.githubusercontent.com/assets/27014552/25233954/f63e0b28-25b6-11e7-9bab-d9eecba38afb.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
