### ISSUE TITLE
Siniestro/ Versión 1.0/ Registrar Siniestro, Datos Accidentado(2)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#22]
* El control “Mail” es el único que permitirá caracteres especiales (Ej: “@”, “.”), permite caracteres especiales en cualquier campo.
![datosaccidentado](https://cloud.githubusercontent.com/assets/27014552/25234379/47060c76-25b8-11e7-93dc-04fbe3c3fc8b.jpg)

* Cuando se selecciona "Provincia" & Partido devuelve msj de error.
![altausuario](https://cloud.githubusercontent.com/assets/27014552/25234412/5ddd3dde-25b8-11e7-946b-9bc91dcf6404.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
