### ISSUE TITLE
Siniestros/ Versión 1.0/ Registrar Siniestro, Evaluación Social(5)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#24]
*  DropDown “Seguro”: Si se sabe que NO posee, elegir “No", no aparece la opción para seleccionarla.
![seguro](https://cloud.githubusercontent.com/assets/27014552/25234839/ae41c9f6-25b9-11e7-9482-7ceb6a8d2874.jpg)

* El Control “Posee trabajo” dice "Independencia" y debería ser "Independiente" .
![poseetrabajo](https://cloud.githubusercontent.com/assets/27014552/25235371/53fd60a2-25bb-11e7-9ee5-3b9eec9cad36.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
