### ISSUE TITLE
Siniestro/ Versión 1.0/ Registrar Siniestro, Intervención ANSV(6)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#25]
* Se deberá cargar en la base las direcciones de la ANSV en caso de que el control “Intervención a otra dirección de ANSV” se seleccione en "SI".
![intervencionansv](https://cloud.githubusercontent.com/assets/27014552/25235757/801d8472-25bc-11e7-811a-35ef1fceab44.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
