### ISSUE TITLE
Siniestro/ Versión 1.0/ Log(2)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#26]
* Desde la pantalla de login se deberá quitar. ya que no cumplen ninguna función.
![log](https://cloud.githubusercontent.com/assets/27014552/25243527/b297ba50-25d3-11e7-8b6b-a27ffef2a6dd.jpg)

* También de se deberá quitar el cartel.
![quitar](https://cloud.githubusercontent.com/assets/27014552/25243568/d80e5b36-25d3-11e7-8c35-8f7cf26858c8.jpg)
tendrá que ingresar al sistema directamente.

* Cambiar el color de la fuente y cambiar "Ingrese a su cuenta" por "Auntenticación de Usuarios".
![log2](https://cloud.githubusercontent.com/assets/27014552/25243645/285ab6fc-25d4-11e7-8167-3fd442f2c459.jpg)

* Si olvidaste tu contraseña dice "haga click aquí" no funciona, no hace nada...
![contrasena](https://cloud.githubusercontent.com/assets/27014552/25243752/88239a4a-25d4-11e7-8c28-634e44948fd5.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
