### ISSUE TITLE
Siniestro/ Versión 1.0/ Consulta Perfil(3).

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#27]
* Acortar los campos "nombre" y "estado" (REPLICAR EN TODAS LAS PANTALLAS DE CONSULTA).
![acortarcamps](https://cloud.githubusercontent.com/assets/27014552/25245160/d8cc1a3a-25d9-11e7-8d10-553c84161881.jpg)

* Cuando se ingresa al menú de consulta, la grilla no debe aparecer si no se realizó una consulta. (ESTE PUNTO REPLICAR EN TODAS LAS PANTALLAS DE CONSULTA).
![noconsulta](https://cloud.githubusercontent.com/assets/27014552/25245236/26308f0e-25da-11e7-9848-14e74c2e5886.jpg)

*Deben ser misma fuente y color (REPLICAR EN TODAS LAS PANTALLAS DE CONSULTA).
![fuente](https://cloud.githubusercontent.com/assets/27014552/25245481/eb40e1a4-25da-11e7-8cd9-c321079e57cd.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.

**Comment by LeandroImoli** [comment]
*  Cuando se ingresa al menú "Consulta Perfiles",  la grilla no aparece correctamente, pero luego si se hace una consulta e ingreso Ej: a la pág. N° 3 y navego por otras pantallas, cuando vuelvo a ingresar a "Consulta Perfiles" sigue mostrando la última consulta que se realizó. (REPLICAR EN TODAS LAS PANTALLAS DE CONSULTA).

![consulta1](https://cloud.githubusercontent.com/assets/27014552/25707721/cf593f78-30ba-11e7-91cf-2aa0cbcbbfa3.jpg)

* si se selecciona buscar "Por Filtro" debe ser obligatorio consultar por "Nombre" o "Estado" en caso de no completar ninguno de los dos campos debe mostrar un msj de recordatorio y no mostrar ningun resultado.
![consulta2](https://cloud.githubusercontent.com/assets/27014552/25708123/edb1112a-30bb-11e7-9225-b09dd5af388d.jpg)


* En caso de editar el Nombre y Permisos de un Perfil que ya existe, la operación se realiza con éxito, debe mostrar un msj de que ese perfil ya existe. Hoy te permite realizar la edición.

* Alinear el botón "Consultar" (rEPLICAR EN LA PANTALLA "CONSULTA USUARIOS).
![consulta3](https://cloud.githubusercontent.com/assets/27014552/25708401/c23f1022-30bc-11e7-8931-5e1d6deafa74.jpg)
