### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuarios (5)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#28]
* Que se pueda editar un usuario (todos los campos menos el Nombre Usuario) y cambiar/agregar/quitar el Perfil.

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.

**Comment by LeandroImoli** [comment]
* Quitar del msj "Resultado de la operación:" (REPLICAR EN TODOS LAS PANTALLAS).
![quitar](https://cloud.githubusercontent.com/assets/27014552/25747119/ceda9336-317c-11e7-86ce-ef346fc2b7ef.jpg)

* Separar por ítems en caso de que e msj sea. "Las contraseñas no coinciden.No se han completado todos los campos obligatorios."
![quitar2](https://cloud.githubusercontent.com/assets/27014552/25747467/f7c02eea-317d-11e7-9f58-f6b0092c2f60.jpg)

* Alinear el botón "Guardar".
![alinear](https://cloud.githubusercontent.com/assets/27014552/25747551/35d527bc-317e-11e7-9a36-e39a4b054cb3.jpg)

**Comment by LeandroImoli** [comment]
* Quitar del msj "Resultado de la operación:" (En la pantalla "Agregar Perfil no se quitó". ).
* Cuando se completan los campos Nombre y Apellido una vez que se escriben no se pueden borrar. (OCURRE EN FIREFOX).
![nombape](https://cloud.githubusercontent.com/assets/27014552/26117009/7e84e1bc-3a3b-11e7-8d4c-8a9713a84819.jpg)
