### ISSUE TITLE
Siniestros/ Versión 1.0/ Perfiles(2)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#29]
* Que se pueda ver los menú que tiene cargado cada perfil y que se puedan editar los mismos.
* Permite crear perfiles con todas las pantallas desactivadas.
* En la grilla cambiar "Nombre" por "Menú".
![pantalla](https://cloud.githubusercontent.com/assets/27014552/25277997/516a4564-2677-11e7-8ef3-843a64ad4ce3.jpg)

* Agregar tilde a "Menú Principal".
![mp](https://cloud.githubusercontent.com/assets/27014552/25278037/8109a5b2-2677-11e7-9527-d536941a134f.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.

**Comment by LeandroImoli** [comment]
* Cuando se da de alta un perfil (exitosamente), y vamos a dar de alta otro y seleccionamos un menú muestra los menú seleccionados del perfil que se dio de alta anteriormente. 
![consulta4](https://cloud.githubusercontent.com/assets/27014552/25710030/64854b68-30c1-11e7-8420-7174fbcd22cb.jpg)
