### ISSUE TITLE
Siniestros/Versión 1.0/Agregar Perfil (1)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#3]
Cuando completamos el campo "Nombre" y el campo "Estado" y hacemos click en el botón "Guardar" devuelve msj que no se ha podido crear correctamente.

![agregarperfil](https://cloud.githubusercontent.com/assets/27014552/24865634/3dce3e8a-1dde-11e7-80bd-764bacff4f40.jpg)

**Comment by leoimoli** [comment]
Se subió a testing el 18/04.

**Comment by LeandroImoli** [comment]
Permite dar de alta Perfiles que ya existen, mismo nombre y mismos permisos.
![perfilesiguales](https://cloud.githubusercontent.com/assets/27014552/25184766/c517d954-24f1-11e7-8782-9784669d3402.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
