### ISSUE TITLE
Siniestros/ Versión 1.0/ Registrar Siniestro

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#30]
* El botón "guardar" cambiar por "Finalizar"
![cargar](https://cloud.githubusercontent.com/assets/27014552/25278413/397d4bf2-2679-11e7-8d89-c28896519e3e.jpg)

* Se deberá quitar los msj que muestra en verde guardando los datos del denunciante.
![rs1](https://cloud.githubusercontent.com/assets/27014552/25278492/83a2dba2-2679-11e7-9950-2632a9acd17e.jpg)

* Agregar un botón "CANCELAR" en todas las pestañas que realice un "borrarlógico" de todo lo que esté cargado.

* Cuando se finalice la carga de un registro siniestro exitoso debe mostrar un cartel de confirmación,
"El siniestro se ha guardado correctamente con el N° 999". **(REPLICAR EL CARTEL DE MSJ EN TODAS LAS PANTALLAS DE ALTA).**
![image](https://cloud.githubusercontent.com/assets/27014552/25278599/147aefde-267a-11e7-9660-abcb41eda7cf.png)

** * Puntos a parte: intentar que las pantallas no refresquen tanto al hacer click en botones o carga de campos, etc.**

** * Si se puede que sea un azul mas claro.**
![azul](https://cloud.githubusercontent.com/assets/27014552/25278740/baad5b44-267a-11e7-9c0f-da691547bf20.jpg)

** * Quitar.**
![2016](https://cloud.githubusercontent.com/assets/27014552/25278917/33a1e63c-267b-11e7-9227-119f7bde2951.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
