### ISSUE TITLE
Siniestros/ Versión 1.0/ Consultar Siniestros (1)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#31]
* Cuando ingresamos a la pantalla "Consultar Siniestro" no debe realizar la consulta.
![cs1](https://cloud.githubusercontent.com/assets/27014552/25279334/7b3bd6c8-267c-11e7-9e9c-40d957130490.jpg)

* El botón "Limpiar" no está funcionando (separar un poco del botón "Consultar").
![cs2](https://cloud.githubusercontent.com/assets/27014552/25279414/c2ce8d82-267c-11e7-86e5-9004ad608676.jpg)

* Alinear los campos y achicar los campos fechas.
![cs3](https://cloud.githubusercontent.com/assets/27014552/25279557/2ed3d618-267d-11e7-8b61-e814a6e32f96.jpg)

* Quitar la hora de la "fecha de carga".
![cs4](https://cloud.githubusercontent.com/assets/27014552/25279622/6f765236-267d-11e7-9ee5-4987de3810a7.jpg)

* Si quiero consultar un siniestro por fecha Ej: cargué un siniestro con la fecha 21/04/2017, para que me lo muestro tengo que consultar en "fecha Desde" por 20/04/2017, si consulto por el 21/04/2017 no me lo trae (me dice que no hay siniestro cargado).

* Cuando quiero consultar por Provincia, al seleccionar una provincia hace la consulta sin hacer click en el botón "Consultar".  Y si selecciono un partido devuelve msj de error.
![cs6](https://cloud.githubusercontent.com/assets/27014552/25280289/cfafdaf8-267f-11e7-9428-4ca675abed19.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.

**Comment by LeandroImoli** [comment]
* El botón "Limpiar" no borra el campo Tipo Documento.
* Así deben quedar los campos fecha.
![consultasis](https://cloud.githubusercontent.com/assets/27014552/25852355/762ef828-349f-11e7-8e92-7dd4e2cf9b37.png)

* Cuando se quiere realizar consultar por el campo fecha rompe, Ej: si estamos en la pantalla de consultar siniestros y hacemos click sobre "Consultar Siniestros" los campos fechas se muestran con hora, si se quiere seleccionar una provincia no te lo permite(te debe poder dejar seleccionar Provincia/Partido..)
![consultarsis1](https://cloud.githubusercontent.com/assets/27014552/25852781/f2082e00-34a0-11e7-987b-42c982357f50.jpg)
