### ISSUE TITLE
Siniestro/ versión 1.0/ Consultar Siniestro, Ver (2)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#32]
* Al seleccionar "VER" de un siniestro pestaña "Dato Denunciante" quitar la hora en Fecha de carga 
![ver1](https://cloud.githubusercontent.com/assets/27014552/25280404/34124ae4-2680-11e7-8e3e-fcfc10196ae1.jpg)

* Agregar el N° del siniestro que se está mostrando 
![ver2](https://cloud.githubusercontent.com/assets/27014552/25280625/0325aaec-2681-11e7-82f1-40b2d1178642.jpg)

* En caso de que el campo vaya vacío porque no es obligatorio, en el detalle que se muestre con un guión ** "-" ** hoy los muestra "No Hay datos" o "NO ESPECÍFICA" .
![ver4](https://cloud.githubusercontent.com/assets/27014552/25280940/0cccaaf4-2682-11e7-9324-948035226d7d.jpg)

* El botón solo debe decir Volver.
![ver5](https://cloud.githubusercontent.com/assets/27014552/25281205/fb3341b2-2682-11e7-968b-377cce57eee7.jpg)

* Faltaria agregar el Botón "Imprimir" para darle la posibilidad al Usuario.
![image](https://cloud.githubusercontent.com/assets/27014552/25281258/2c49ebd4-2683-11e7-8ec5-e56d2f026eb9.png)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.

**Comment by LeandroImoli** [comment]
* Al querer imprimir el siniestro devuelve lo siguiente.
![imp](https://cloud.githubusercontent.com/assets/27014552/25853115/face345c-34a1-11e7-981d-4f0a875b7859.jpg)
