### ISSUE TITLE
SIniestros/ Versión 1.0/ Consultar Siniestro (3)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#33]
* Una vez que se dio de alta un siniestro, hay 15 minutos para poder editar el siniestro, no está apareciendo la opción.
![editar](https://cloud.githubusercontent.com/assets/27014552/25281702/8760de96-2684-11e7-8f13-ab27e450aa18.jpg)

* Cambiar el nombre de la columna en la grilla "Ver" por "Detalle".
![detalle](https://cloud.githubusercontent.com/assets/27014552/25281857/1b793510-2685-11e7-8ad4-0c5922e9c310.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
