### ISSUE TITLE
Siniestro/ Versión 1.0/ Registro Siniestro

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#34]
* Pestaña Datos Denunciantes : si seleccionamos Tipo de Documento "Pasaporte", N° Documento "36273257A" y la Provincia "Salta"  me borra todo...
![salta](https://cloud.githubusercontent.com/assets/27014552/25282722/b7074088-2687-11e7-96c2-5f515d45d2b9.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.

**Comment by LeandroImoli** [comment]
* Ahora pasa con la provincia Misiones...

**Comment by LeandroImoli** [comment]
* Sigue ocurriendo una vez que hacemos click en el botón cancelar, y luego seleccionamos una provincia en la pestaña "Dato Denunciante" te autodirige a la pestaña "Evaluación Jurídica".
