### ISSUE TITLE
Legales/ Versión 1.0/ Convenios

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#37]
* Al querer eliminar un convenio si bien se da de baja correctamente,  la columna "Estado" de la grilla se borra.
![borrar](https://cloud.githubusercontent.com/assets/27014552/25662479/17b57b54-2feb-11e7-89b2-8873ac07cac8.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 03/05/2017.
