### ISSUE TITLE
Siniestros/Versión 1.0/ Agregar Perfil

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#4]
En esta pantalla quedaría agregar que permisos y acceso tendrá el perfil , Ej: si se agrega un Perfil Consulta de Siniestros, se debería poder seleccionar que este perfil  debería solo poder acceder a la pantalla "Consultar Siniestros".

**Comment by leoimoli** [comment]
Se subió a testing el 18/04.
