### ISSUE TITLE
AlcoStock/ Versión 1.1/ Alta de Bienes

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#40]
* Al dar de alta un bien devuelve el siguiente msj de error. (No insert el historial de responsable).
![motivomovimiento](https://cloud.githubusercontent.com/assets/27014552/26589322/21002bf2-452e-11e7-9c81-b955fae8d42c.jpg)

**Comment by leoimoli** [comment]
Subido a testing el 06/06.
