### ISSUE TITLE
AlcoStock/ Versión 1.1/Dar de baja Biene

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#41]
* Una vez que se dio de baja un bien en la grilla no se debe mostrar la opción de eliminar ya que se encuentra dado de baja.
![eliminaralco](https://cloud.githubusercontent.com/assets/27014552/26587929/30bcc2f2-452a-11e7-8f92-992698f5923d.jpg)

**Comment by LeandroImoli** [comment]
* Cuando quiero buscar por la combinación de filtros Naturaleza, N° serie e incluidos los dados de bajas no me trae ningún resultado, ej: Naturaleza: 435- Equipo Educacional y Recreativo, N° Serie: 5398
![baja](https://user-images.githubusercontent.com/27014552/26847473-9587ed70-4ad3-11e7-9799-2daf4168a824.jpg)

**Comment by leoimoli** [comment]
Subido a testing el 06/06.
