### ISSUE TITLE
AlcoStock/ Versión 1.1/Gestión Comodato

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#43]
* Una vez que agregas el comodato muestra "2017" en el año cuando tal vez el año era 2016. Desp. muestra bien el año!
![altacomodatoanodis](https://cloud.githubusercontent.com/assets/27014552/26595401/a75b3f6c-4541-11e7-8aa2-33cf59b90834.jpg)
(EN EDITAR TAMBIÉN MUESTRA MAL).
![edit](https://cloud.githubusercontent.com/assets/27014552/26596036/c43c9cb4-4543-11e7-96dd-d10280cd7916.jpg)
* Cuando editas devuelve el siguiente error.
![edit2](https://cloud.githubusercontent.com/assets/27014552/26596579/a175555c-4545-11e7-9eb9-1457fe3c2920.jpg)

* Al querer dar de alta un comodato  Prov/Muni devuelve msj de error.
![comodato1](https://cloud.githubusercontent.com/assets/27014552/26595418/bb5354d2-4541-11e7-803f-012d0b528018.jpg)

* Cuando voy a dar de alta un Comodato, su N° de comodatos es el último agregado +1, Hoy no está funcionado correctamente ya que cuando doy de alta uno y consultó me trae dos resultados con el mismo número de comodato.
![comodato 1](https://cloud.githubusercontent.com/assets/27014552/26595540/23137fb6-4542-11e7-80b9-72e806db9bff.jpg)

* Cuando agregamos un nuevo comodato, abajo nos aparece el botón Agregar Nuevo Comodato...
![agrnuevocomodato](https://cloud.githubusercontent.com/assets/27014552/26595710/b6abe3d0-4542-11e7-9463-d6c616d93abf.jpg)
Si seleccionamos ese botón todos los campos se deberán mostrar vacíos menos el Número de comodato que se generará automáticamente.
![nc](https://cloud.githubusercontent.com/assets/27014552/26595851/187d103e-4543-11e7-9697-ac7ec0c5f88d.jpg)

**Comment by leoimoli** [comment]
Subido a testing el 06/06.

**Comment by LeandroImoli** [comment]
* Cuando voy a dar de alta un Comodato, su N° de comodatos es el último agregado +1, Hoy no está funcionado correctamente ya que cuando doy de alta uno y consultó me trae dos resultados con el mismo número de comodato (ESTO SIGUE SUCEDIENDO, NO ESTÁ YENDO A BUSCAR EL ÚLTIMO COMODATO) 
* Al agregar bienes a un comodato (NUEVO RECIÉN AGREGADO) devuelve msj de error.. Ej; con el comodato N° 1364
![agregarbienes](https://user-images.githubusercontent.com/27014552/26945256-8ba97776-4c61-11e7-9511-5527c9f56296.jpg)

* Al ingresar en "Agregar Bienes" se muestra de la siguiente manera.
![comodatos](https://user-images.githubusercontent.com/27014552/26945298-af1db1e0-4c61-11e7-9733-26f158744b2a.jpg)
