### ISSUE TITLE
AlcoStock/ Versión 1.1/Motivo Movimiento

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#44]
* Al querer registrar un Motivo movimiento al hacer click en el botón guardar no hace nada.
![altamotivo](https://cloud.githubusercontent.com/assets/27014552/26634334/ac668696-45ec-11e7-9611-734ffa6615fd.jpg)

**Comment by leoimoli** [comment]
Subido a testing el 06/06.

**Comment by LeandroImoli** [comment]
* Al buscar por el tipo Responsable/Ub Física si bien la página 1 la muestra bien, cuando seleccionamos las 2 no muestra nada.
![pag](https://user-images.githubusercontent.com/27014552/26884511-4e14205a-4b76-11e7-9f79-1c895d674c47.jpg)

*Una vez que se dio de alta un motivo cuando vamos a filtros que refresque, queda filtrado la última búsqueda que se realizó

**Comment by leoimoli** [comment]
En testing 07/06.
