### ISSUE TITLE
AltoStock/ Versión 1.1/ Bienes, ALTA ALCOLIMETRO

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#45]
* Si selecciona un Tipo de Bien, muestra todos las MARCAS, solo debe mostrar las del bien seleccionado.
![altaalco](https://cloud.githubusercontent.com/assets/27014552/26635230/7fe082cc-45ef-11e7-8502-ddfe4c6eeeb3.jpg)

**Comment by leoimoli** [comment]
Subido a testing el 06/06.
