### ISSUE TITLE
Siniestros/Versión 1.0/Consultar Perfil(1)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#5]
El Radio Button "Buscar Por" por defecto debe estar seleccionado "Todos", hoy viene seleccionado "Por Filtros".

![consultaperfiles](https://cloud.githubusercontent.com/assets/27014552/24866557/d958e9de-1de0-11e7-9d64-c2091342f982.jpg)

**Comment by leoimoli** [comment]
Se subió a testing el 18/04.
