### ISSUE TITLE
Sinai-Sinat/V1.13.9/Registrar Antecedentes, Curso Seguridad Vial

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#57]
* Campo Calificación: Permite que sea Negativo, Solo debe permitir que tengo hasta dos de decimales ( nn,nn),  Ej: permite 100,50 ; 10,500 ; -9. Este campo debe ser solo numérico.

* Se debería agregar los (*) cuando el campo es obligatorio según el Tipo Antecedente (ESTE PUNTO SE DEBERÍA REPLICAR EN TODOS LOS TIPOS ANTECEDENTES).

* Permite cargar el curso sin fecha finalización con calificación y APROBADO/DESAPROBADO...
![image](https://user-images.githubusercontent.com/27014552/28781821-c028e942-75e1-11e7-919b-f0cf750f35aa.png)
* Cambiar msj cuando: Fecha Inicio es mayor a la fecha Finalización ej: 01/07/2017 - 01/06/2017.
El msj debe ser: "La fecha Inicio debe ser menor o igual a la fecha Finalización. Hoy lo muestra de la siguiente manera.
![image](https://user-images.githubusercontent.com/27014552/28782583-f4095542-75e3-11e7-9083-126a3e659b94.png)

**Comment by LeandroImoli** [comment]
* El curso realizó se está agregando en la grilla de "Antecedentes Externos" cuando debe ir en la grilla de "Cursos"...
![curso_sv](https://user-images.githubusercontent.com/27014552/30930471-2f727b68-a398-11e7-9262-f8eec212cde0.jpg)

* El campo "Calificación" debe ser opcional ya que dicen que a veces manda solo aprobado/desaprobado  (ambos si se mantendrán como obligatorios). El campo "Calificación" si es posible debe permitir solo dos decimales ya que hoy sigue permitiendo Ej: 7,1555.

**Comment by leodimonio** [comment]
El Curso va dentro de los antecedentes externos ya que en cursos van los obtenidos por el sistema de renatedu(
El curso realizó se está agregando en la grilla de "Antecedentes Externos" cuando debe ir en la grilla de "Cursos"...)

**Comment by LeandroImoli** [comment]
Se debería quitar * del campo "Calificación" ya que no es mas un campo obligatorio...
![image](https://user-images.githubusercontent.com/27014552/32057535-e9bee432-ba3d-11e7-9d70-18af7f634f0c.png)
