### ISSUE TITLE
Siniestros/ Versión 1.0/Consultar Perfil(2)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#6]
Al querer desactivar un perfil haciendo click en el botón "Desactivar" devuelve msj de error, "Error.
An error occurred while processing your request".

![btndesahbilitarconsultaperfiles](https://cloud.githubusercontent.com/assets/27014552/24866741/7771a7e6-1de1-11e7-96ab-cff834539121.jpg)

**Comment by leoimoli** [comment]
Se subió a testing el 18/04.

**Comment by LeandroImoli** [comment]
* Si un Perfil se encuentra desactivado
![perconsul1](https://cloud.githubusercontent.com/assets/27014552/25184227/3e21a98a-24f0-11e7-8f44-27e99af32db0.jpg)
Cuando Vamos a dar de alta un usuario los perfiles que se encuentran desactivados no se deberían poder seleccionar.
![perdesacusuario](https://cloud.githubusercontent.com/assets/27014552/25184377/a30306be-24f0-11e7-8b96-dc818cc1a2b7.jpg)

**Comment by leoimoli** [comment]
Se subio a testing el 02/05.
