### ISSUE TITLE
Siniestros/ Versión 1.0/ Munú Principal

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#7]
En el menú principal cambiar de lugar "Consultar Usuarios" con "Agregar Usuarios".

![menuprincipal](https://cloud.githubusercontent.com/assets/27014552/24867038/5b3cb164-1de2-11e7-863d-73f3a22da4ad.jpg)

**Comment by leoimoli** [comment]
Se subió a testing el 18/04.
