### ISSUE TITLE
AlcoStock/V2.1.0/Eliminar bienes de un comodato

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#70]
* Cuando eliminamos un bien que está asociado a un comodato si bien se realiza con éxito, en el historial del bien "Historial Responsable" no está mostrando el cambio...
![historial_ub_resp](https://user-images.githubusercontent.com/27014552/30340991-c478956e-97ca-11e7-9924-355d62b33595.jpg)

* Tampoco actualiza la ubicación física/responsable del mismo...
![image](https://user-images.githubusercontent.com/27014552/30341025-f32960be-97ca-11e7-948d-a81c55e58f1a.png)
![image](https://user-images.githubusercontent.com/27014552/30341134-50ed813a-97cb-11e7-9c20-498943cf351d.png)

**Comment by LeandroImoli** [comment]
* Ahora cuando se elimina un bien del comodato y el tipo de Ub. Física es "Comodato" Provincia en la grilla lo muestra como comodato y no la provincia...
![image](https://user-images.githubusercontent.com/27014552/31280953-6dfa5f98-aa84-11e7-841e-754276678c20.png)

**Comment by LeandroImoli** [comment]
* Cuando se elimina un bien del comodato, Tipo de ubicación física/Responsable "COMODATO" se debe replicar la funcionalidad de que solo se pueda seleccionar Provincia sin la necesidad de seleccionar "Municipio"... Devuelve los siguientes msj de error, igualmente se realiza con éxito el cambio 
![image](https://user-images.githubusercontent.com/27014552/32000217-58c0f122-b96c-11e7-802b-56b5acfb2bf7.png)
![image](https://user-images.githubusercontent.com/27014552/32000245-74fde976-b96c-11e7-814c-87a944e8fe12.png)

* Se están pisando los estados cuando se elimina un bien de un comodato... En el historial Responsable no inserta el motivo correcto
![image](https://user-images.githubusercontent.com/27014552/32003492-9cdeb782-b975-11e7-948b-3bb818bcaecb.png)

* Replicar en caso que sea Provincia/Municipio...
![image](https://user-images.githubusercontent.com/27014552/32003768-762b6ecc-b976-11e7-9e84-0309c9b397c3.png)

**Comment by leoimoli** [comment]
También se solicitó que el motivo de baja de un bien asociado a un comodato, sea guardado por igual para el historial de responsables como para ubicación física, el problema es que la tabla de historial de responsables solamente contiene una columna idMotivo, y no un campo "libre" para ingresar el motivo, en caso de querer que se guarde en ambos, habría que agregar una columna en la tabla historial responsable.
