### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuario(1)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#8]
Al querer agregar un usuario al darle al botón guardar devuelve msj de error, "Error.
An error occurred while processing your request".

![altausuario](https://cloud.githubusercontent.com/assets/27014552/24867285/1bba3aec-1de3-11e7-8950-ecbe866aac6a.jpg)

**Comment by leoimoli** [comment]
Se subió a testing el 18/04.

**Comment by LeandroImoli** [comment]
* Sigue devolviendo msj de error al querer cargar un nuevo Usuario.

![altausuario](https://cloud.githubusercontent.com/assets/27014552/25146597/d783f796-244a-11e7-86c7-41585c638a69.jpg)
