### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuario (2)

### ISSUE THREAD

**Issue by LeandroImoli** [leoimoli/Testing#9]
El campo "Fecha de Alta" solo debe ser de fecha, hoy deja agregar caracteres de texto

![altausuariofecha](https://cloud.githubusercontent.com/assets/27014552/24867493/c08e1aac-1de3-11e7-87b5-0008504db039.jpg)

**Comment by leoimoli** [comment]
Se subió a testing el 18/04.
